export const validationRanges = [
  { field: 'Plant', required: true, type: 'Select', allowedValues: ['Eirich', 'Disa', 'Foundry-A'] },
  { field: 'Date', required: true, type: 'Date' },
  { field: 'R. Sand (Kgs/Mix)', required: false, type: 'Text', description: 'No fixed range documented' },
  { field: 'N. Sand (Kgs/Mould)', required: false, type: 'Text', description: 'No fixed range documented' },
  { field: 'Mixing Mode', required: false, type: 'Text', description: 'No fixed range documented' },
  { field: 'Bentonite (Kgs/Mix) - Table 1', required: false, type: 'Text', description: 'No fixed range documented' },
  { field: 'Coal Dust / Premix (Kgs/Mix)', required: false, type: 'Text', description: 'No fixed range documented' },
  { field: 'Total Clay', required: false, type: 'Number', unit: '%', min: 11.0, max: 14.5 },
  { field: 'Active Clay', required: false, type: 'Number', unit: '%', min: 8.5, max: 11.0 },
  { field: 'Dead Clay', required: false, type: 'Number', unit: '%', min: 2.0, max: 4.0 },
  { field: 'V.C.M.', required: false, type: 'Number', unit: '%', min: 2.0, max: 3.2 },
  { field: 'L.O.I.', required: false, type: 'Number', unit: '%', min: 4.5, max: 6.0 },
  { field: 'AFS No.', required: false, type: 'Number', min: 48, description: 'Minimum 48' },
  { field: 'Fines', required: false, type: 'Number', unit: '%', max: 10, description: 'Maximum 10%' },
  { field: 'Mix No. Start / End', required: false, type: 'Text', description: 'No fixed range documented' },
  { field: 'Mix No. Total', required: false, type: 'Number', description: 'Auto-computed as End - Start; not editable' },
  { field: 'No. Of Rejected', required: false, type: 'Text', description: 'No fixed range documented' },
  { field: 'Return Sand Hopper Level', required: false, type: 'Text', description: 'No fixed range documented' },
  { field: 'Sand Lumps', required: false, type: 'Text', description: 'No fixed range documented' },
  { field: 'New Sand Wt', required: false, type: 'Text', description: 'No fixed range documented' },
  { field: 'Prepared Sand Friability', required: false, type: 'Number', unit: '%', min: 8.0, max: 13.0 },
  { field: 'Time', formKey: 'time', required: false, type: 'Time' },
  { field: 'Mix No (Table 5)', formKey: 'mixNo', required: false, type: 'Number' },
  { field: 'Permeability', formKey: 'permeability', required: false, type: 'Number', min: 90, max: 160 },
  { field: 'G.C.S FDY-A', formKey: 'gcsValue', required: false, type: 'Number', unit: 'Gm/cm²', min: 1800, description: 'Minimum 1800' },
  { field: 'G.C.S FDY-B', required: false, type: 'Number', unit: 'Gm/cm²', min: 1900, description: 'Minimum 1900' },
  { field: 'WTS', formKey: 'wts', required: false, type: 'Number', unit: 'N/cm²', min: 0.15, description: 'Minimum 0.15' },
  { field: 'Moisture', formKey: 'moisture', required: false, type: 'Number', unit: '%', min: 3.0, max: 4.0 },
  { field: 'Compactability At Dmm', formKey: 'compactability', required: false, type: 'Number', unit: '%', min: 33, max: 40 },
  { field: 'Compressability At Dmm', formKey: 'compressability', required: false, type: 'Number', unit: '%', min: 20, max: 28 },
  { field: 'Water Litre/Kg Mix', formKey: 'waterLitreKgMix', required: false, type: 'Number', min: 0 },
  { field: 'Sand Temp BC', formKey: 'sandTempBC', required: false, type: 'Number', unit: '°C', min: 0, max: 45 },
  { field: 'Sand Temp WU', formKey: 'sandTempWU', required: false, type: 'Number', unit: '°C', min: 0, max: 45 },
  { field: 'Sand Temp SSU', formKey: 'sandTempSSU', required: false, type: 'Number', unit: '°C', min: 0, max: 45 },
  { field: 'New Sand Kgs/Mould', formKey: 'newSandKgsMould', required: false, type: 'Number', min: 0.0, max: 5.0 },
  { field: 'Bentonite % (0.60-1.20 checkpoint)', formKey: 'bentonitePercent', required: false, type: 'Number', unit: '%', min: 0.60, max: 1.20 },
  { field: 'Bentonite % (0.80-2.20 checkpoint)', required: false, type: 'Number', unit: '%', min: 0.80, max: 2.20 },
  { field: 'Premix % (Premix checkpoint)', formKey: 'premixCoalPercent', required: false, type: 'Number', unit: '%', min: 0.60, max: 1.20 },
  { field: 'Coal Dust % (CoalDust checkpoint)', required: false, type: 'Number', unit: '%', min: 0.28, max: 0.70 },
  { field: 'Compactability Setting Value', formKey: 'compactabilityValue', required: false, type: 'Number', min: 0 },
  { field: 'Mould Strength Setting Value', formKey: 'mouldStrengthValue', required: false, type: 'Number', min: 0 },
  { field: 'Prepared Sand Lumps/Kg', formKey: 'preparedSandLumpsKg', required: false, type: 'Number', min: 0 },
  { field: 'Item Name', formKey: 'itemName', required: false, type: 'Text' },
  { field: 'Remarks', formKey: 'remarks', required: false, type: 'Text' }
];
